### PR TITLE
Doc fixes

### LINKED ISSUE #60: test_result needs matching api and return value

### PR DESCRIPTION
**Pull request by chendaniely**
Documentation updates and fixes

Does not fix #60 that's in another PR (#63)

### CODE REVIEW

File: R/check_code.R [hunk 1]
```diff
@@ -18,7 +21,8 @@
 #' 2. Make a "-solution" code chunk for the exercise to be checked in a learnr
 #' document. There is no need to supply a solution argument for
 #' \code{check_code()} if you call it from the "-check" chunk of the same
-#' exercise. Likewise, there is no need to supply a user argument when you call
+#' exercise. Likewise, there is no need to supply a student submitted code
+#' argument when you call
```
Comment (schloerke) [inline R/check_code.R]: `call it.`?

File: R/check_code.R [hunk 2]
```diff
@@ -30,16 +34,22 @@
 #' @template learnr_args
 #' @template glue_correct
 #' @template glue_incorrect
-#' @param glue_pipe A glue string that returns the final message displayed when a user uses a pipe,
+#' @param glue_pipe A glue string that returns the final message displayed when
+#'    the studentuses a pipe,
```
Comment (schloerke) [inline R/check_code.R]: missing space.

are we doing `student` or `user`?

File: R/check_code.R [hunk 3]
```diff
@@ -30,16 +34,22 @@
...
 #'   the message will be the content of the \code{glue_pipe} argument.
 #'
+#' @seealso \code{\link{check_code}}, \code{\link{check_result}}, and \code{\link{test_result}}
 #' @export
 #' @examples
 #' \dontrun{grading_demo()}
+#'
+#' y <- quote(sqrt(log(2)))
+#' z <- quote(sqrt(log(1)))
+#' check_code(grader_args = list(user_quo = y, solution_quo = z))
```
Comment (schloerke) [inline R/check_code.R]: add a comment about this being a manual example.  "See grading demo for tutorial usage."

File: R/condition.R [hunk 4]
```diff
@@ -13,6 +16,11 @@
 #'   whether or not the expression is the correct answer or not, \code{correct},
 #'   the type of expression (formula, function, or value), \code{type}
 #' @export
+#'
+#' @examples
+#' \dontrun{
```
Comment (schloerke) [inline R/condition.R]: is there a reason for the `\dontrun`?

File: R/evaluate_condition.R [hunk 5]
```diff
@@ -1,12 +1,22 @@
-#' Evaluates a condition
+#' Evaluates a conditio
```
Comment (schloerke) [inline R/evaluate_condition.R]: missing `n`

File: R/evaluate_condition.R [hunk 6]
```diff
@@ -1,12 +1,22 @@
...
 #'
-#' @param condi a \code{grader} \code{\link{condition}} object
+#' Evaluates the \code{\link{condition}} object to return a \code{\link{graded}} value.
+#'
+#' @param condi a \code{\link{condition}} object
```
Comment (schloerke) [inline R/evaluate_condition.R]: should this param now be called `condition`?

File: R/get_code.R [hunk 7]
```diff
@@ -4,21 +4,27 @@
...
+#' @describeIn get_code get student code
 #' @inheritParams rlang::eval_tidy
+#'
+#' @export
 get_user_code <- function(user = NULL, env = rlang::caller_env()) {
   get_code(user, "user", env = env)
 }
+
+#' @describeIn get_code get solution code provided by instructor
+#""
```
Comment (schloerke) [inline R/get_code.R]: odd line

File: R/grade_learnr.R [hunk 8]
```diff
@@ -1,16 +1,14 @@
...
-#' A checker function to use with learnr
-#'
-#' For exercise checking, learnr tutorials require a function that learnr can
+#' For exercise checking, \code{learnr} tutorials require a function that \code{learnr} can
 #' use in the background to run the code in each "-check" chunk and to format
-#' the results into a format that learnr can display. The function must accept a
+#' the results into a format that \code{learnr} can display. The function must accept a
 #' specific set of inputs and return a specific type of output (see \code{\link{graded}}).
-#' Users are not intended to use the function themselves, but to pass it to the
+#' Instructors are not intended to use the function themselves, but to pass it to the
```
Comment (schloerke) [inline R/grade_learnr.R]: "intended to use the \code{grade_learnr} function directly, but to..."

File: R/grade_learnr.R [hunk 9]
```diff
@@ -1,16 +1,14 @@
...
 #' \code{exercise.checker} knitr chunk option within the setup chunk of the
-#' tutorial.
+#' \code{learnr} tutorial.
 #'
-#' The grader package provides \code{grade_learnr} for this purpose. To enable
+#' The \code{gradethis} package provides \code{\link{grade_learnr}} for this purpose. To enable
```
Comment (schloerke) [inline R/grade_learnr.R]: this first sentence seems like a repeat of the prior paragraph. Remove it? (start with `To enable...`)

File: archive/view_tutorial.R [hunk 10]
```diff
@@ -12,7 +12,10 @@
 #'
 #' TODO need to export when feature is implement in RStudio IDE
 #' @noRd
+<<<<<<< HEAD:archive/view_tutorial.R
```
Comment (schloerke) [inline archive/view_tutorial.R]: remove these gitdiff comments

File: R/check_code.R (hunk 1 above)
Comment (chendaniely) [reply R/check_code.R]: the documentation continues on the next line, I just didn't reflow the docstring to make a smaller diff

File: R/check_code.R (hunk 2 above)
Comment (chendaniely) [reply R/check_code.R]: using student/instructor in the documentation (internal code variables may need to be renamed eventually) since there were a few times when the "user" would also refer to the instructor writing the document.

File: R/check_code.R (hunk 3 above)
Comment (chendaniely) [reply R/check_code.R]: but this would be how someone would use `gradethis` as a standalone library

File: R/evaluate_condition.R (hunk 6 above)
Comment (chendaniely) [reply R/evaluate_condition.R]: yes. changed `condi` to `condition`

File: R/condition.R (hunk 4 above)
Comment (chendaniely) [reply R/condition.R]: nope, I thought it would evaluate `.result` (which it doesn't)

File: R/check_code.R (hunk 3 above)
Comment (chendaniely) [reply R/check_code.R]: Added comment about learnr tutorial

File: R/get_code.R (hunk 7 above)
Comment (chendaniely) [reply R/get_code.R]: would "instructor's solution code" be better?

File: R/check_code.R (hunk 1 above)
Comment (schloerke) [reply R/check_code.R]: reflow the docs since it can be done easily within rstudio

File: R/get_code.R (hunk 7 above)
Comment (schloerke) [reply R/get_code.R]: oh! Didn't see what was going on.

Let's not export these two functions: `get_user_code` and `get_solution_code`

File: R/check_code.R (hunk 2 above)
Comment (schloerke) [reply R/check_code.R]: Ok.

Still missing space in `studentuses`

File: R/condition.R (hunk 4 above)
Comment (schloerke) [reply R/condition.R]: remove the `\dontrun`

File: R/grade_learnr.R [hunk 11]
```diff
@@ -1,18 +1,16 @@
...
-#'
-#' For exercise checking, learnr tutorials require a function that learnr can
+#' For exercise checking, \code{learnr} tutorials require a function that \code{learnr} can
 #' use in the background to run the code in each "-check" chunk and to format
-#' the results into a format that learnr can display. The function must accept a
+#' the results into a format that \code{learnr} can display. The function must accept a
 #' specific set of inputs and return a specific type of output (see \code{\link{graded}}).
-#' Users are not intended to use the function themselves, but to pass it to the
+#' Instructors are not intended to use the \code{grade_learnr} function directly,
+#' but to pass it to the
```
Comment (schloerke) [inline R/grade_learnr.R]: reflow as well

File: R/get_code.R (hunk 7 above)
Comment (chendaniely) [reply R/get_code.R]: I also `@noRd`'ed `get_code`
