### PR TITLE
Bring pass_if() and fail_if() to grade_this()

### LINKED ISSUE #197: Bring pass_if() and fail_if() to grade_this()
Using `pass_if()` and `fail_if()` inside `grade_this()` currently doesn't work. 

``` r
grade_this({
  pass_if(.result == 4 && grepl("\\d \\+ \\d", .user_code), "yes")
  fail_if(TRUE, "no")
})(list(
  .result = 4,
  .user_code = "1 + 3"
))
#> $x
#> [1] TRUE
#> 
#> $message
#> [1] "no"
#> 
#> $correct
#> [1] FALSE
#> 
#> $type
#> [1] "value"
#> 
#> attr(,"class")
#> [1] "gradethis_condition"
```

To the end user, this result in a message in the tutorial

```
A problem occurred with your teacher’s grading code. Defaulting to incorrect
```

and a warning in the console:

```
`___-check` chunk did not mark an answer as correct or incorrect.
Consider adding a `pass()` or `fail()` at the end of your `___-check` code
```

Given the prevalence of `pass_if()` and `fail_if()` in existing gradethis code, I think we should make these work for `grade_this()`. If not, at the very least we should have stronger checks with better advice when either are used inside `grade_this()`.

A sketch of what I think we would need to do

- Update the calling handlers in `capture_graded()` to handle a `gradethis_condition`
- That calling handler would turn the `gradethis_condition` into a `gradethis_graded` condition via `graded()`
- Update calls to `capture_graded()`?

### PR DESCRIPTION
**Pull request by gadenbuie**
Brings `pass_if()` and `fail_if()` to `grade_this()` but doesn't allow formulas or functions.

I added a special hidden variable to the `check_env` in `grade_this()` called `.__gradethis_check_env` to enable `detect_grade_this()` to determine if it's being evaluated inside a `grade_this()` call.

Then `pass_if()` and `fail_if()` evaluate differently if they're in the `grade_this()` `check_env`. Using formulas or functions throws a "problem grading" feedback message and a run-time warning.

Fixes #197

### CODE REVIEW

**Comment by gadenbuie** [comment]
Documentation is minimal on this PR, I'll handle that separately later

File: R/grade_result.R [hunk 1]
```diff
@@ -207,31 +207,61 @@ condition <- function(x, message, correct) {
...
 #' @export
 fail_if <- function(x, message = NULL) {
+  env <- parent.frame()
+  if (detect_grade_this(env)) {
+    assert_gradethis_condition_type(x, "fail_if")
+    if (!(x)) {
+      fail(message, env = env)
+    }
+  } else {
   condition(x, message, correct = FALSE)
```
Comment (schloerke) [inline R/grade_result.R:250]:
```suggestion
    condition(x, message, correct = FALSE)
```

File: R/grade_result.R [hunk 2]
```diff
@@ -207,31 +207,61 @@ condition <- function(x, message, correct) {
...
+  }
 }
 
-
+assert_gradethis_condition_type <- function(x, from) {
+  type <- condition_type(x)
+  if (!identical(type, "value")) {
```
Comment (schloerke) [inline R/grade_result.R:256]: thank you

**Review by schloerke — APPROVED** [review]

**Review by schloerke — APPROVED** [review]
