### PR TITLE
Issue 145

### LINKED ISSUE #145: Grading with pipes fails in mysterious ways
```r
# Works
user <- as.expression(rlang::parse_exprs("a <- 2"))
inner_sol <- as.expression(rlang::parse_exprs("a <- 1"))
gradethis::grade_code(correct = "message here", grader_args = list(user_quo = user, solution_quo = inner_sol))

# Works if answer is correct, but throws an error if incorrect.
user <- as.expression(rlang::parse_exprs("1:6 %>% sample(size = 2) %>% sum()"))
inner_sol <- as.expression(rlang::parse_exprs("1:6 %>% sample(size = 2) %>% print"))
gradethis::grade_code(correct = "message here", grader_args = list(user_quo = user, solution_quo = inner_sol))

# Observed errors (depending on the way you get it wrong) include:
# - Error in stop(simpleError(sprintf(msg, ...), call.)) : bad error message
# - "Assertion on '.user' failed: Must be of type 'atomic', not 'expression'.", "Assertion on '.message' failed: Must be of type 'atomic', not 'expression'.", "Assertion on '.incorrect' failed: Must be of type 'atomic', not 'expression'."
# - Error in rhs[[2]] <- lhs : object of type 'symbol' is not subsettable
#    In addition: Warning message:
#    In value[[3L]](cond) : restarting interrupted promise evaluation
```

### PR DESCRIPTION
**Pull request by VincentGuyader**
Fixes #145 

`unpipe` and `unpipe_all` can deal with missing parenthesis in call

### CODE REVIEW

File: R/unpipe.R [hunk 1]
```diff
@@ -16,6 +16,13 @@ unpipe <- function(code) {
   lhs <- code[[2]]
   rhs <- code[[3]]
 
+  if (!is.call(rhs)){
+    # rhs need to be a call
+    # mainly because some user do `1 %>% print` instead of `1 %>% print()`
+    rhs <-  call(deparse(rhs))
+    }
```
Comment (schloerke) [inline R/unpipe.R:23]:
```suggestion
  }
```

File: R/unpipe.R [hunk 2]
```diff
@@ -16,6 +16,13 @@ unpipe <- function(code) {
   lhs <- code[[2]]
   rhs <- code[[3]]
 
+  if (!is.call(rhs)){
```
Comment (schloerke) [inline R/unpipe.R:19]:
```suggestion
  if (!is.call(rhs)) {
```

**Review by schloerke — APPROVED** [review]

**Review by VincentGuyader — COMMENTED** [review]
seems ok for me
