### PR TITLE
fix: Handle a mix of named and unnamed arguments and with pipes

### LINKED ISSUE #215: Unnamed `aes()` argument trips up `grade_this_code()`
@gadenbuie one of my students reported this grade code message misfire today. Notice that the message says he shouldn't have included `x = displ`, which is a mistake. I think we will find something useful to fix if we track it upstream.

```r
grade_this_code()(
  list(
    .user_code = "ggplot(data = mpg, mapping = aes(x = displ, y = hwy, alpha = class, 0.1)) + geom_point()", 
    .solution_code = "ggplot(data = mpg, mapping = aes(x = displ, y = hwy, alpha = class)) + geom_point()"
  )
)

## <gradethis_graded: Incorrect: 
## In `mapping = ggplot(data = mpg, mapping = aes(x = displ, y = hwy, alpha = class, 0.1))`, 
## I did not expect your call to `aes()` to include `x = displ`. You may have included an 
## unnecessary argument, or you may have left out or misspelled an important argument 
## name. Give it another try.>
```

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #215

## Before

```r
grade_code()(mock_this_exercise(
  'band_members %>% filter(name == "Mick")',
  'band_members %>% filter(name == "John")',
  setup_exercise = "library(dplyr)"
))
#> <gradethis_graded: [Incorrect] I see that you are using pipe operators (e.g. %>%),
#> so I want to let you know that this is how I am interpretting your code before I
#> check it:
#> 
#> ```r
#> filter(band_members, name == "Mick")
#> ```
#> 
#> In `band_members %>% filter(name == "Mick")`, I expected you to ``==`()` where you
#> wrote `band_members`.  Let's try it again.>

grade_this_code()(
  list(
    .user_code = "ggplot(data = mpg, mapping = aes(x = displ, y = hwy, alpha = class, 0.1)) + geom_point()", 
    .solution_code = "ggplot(data = mpg, mapping = aes(x = displ, y = hwy, alpha = class)) + geom_point()"
  )
)
#> <gradethis_graded_this_code: [Incorrect] I did not expect your call to `aes()`
#> to include `x = displ`. You may have included an unnecessary argument, or you
#> may have left out or misspelled an important argument name. Let's try it again.>

demo <- function(x = 1, ...) {
  list(x, ...)
}

gradethis::grade_this_code()(
  list(
    .user_code = "demo(x = 1, 2)", 
    .solution_code = "demo(x = 1)"
  )
)
#> <gradethis_graded_this_code: [Incorrect] I did not expect your call to `demo()`
#> to include `x = 1`. You may have included an unnecessary argument, or you may
#> have left out or misspelled an important argument name. Try it again. You get
#> better each time.>
```

## After

```r
grade_code()(mock_this_exercise(
  'band_members %>% filter(name == "Mick")',
  'band_members %>% filter(name == "John")',
  setup_exercise = "library(dplyr)"
))
#> <gradethis_graded: [Incorrect] I see that you are using pipe operators (e.g. %>%),
#> so I want to let you know that this is how I am interpretting your code before I
#> check it:
#> 
#> ```r
#> filter(band_members, name == "Mick")
#> ```
#> 
#> In `name == "Mick"`, I expected `"John"` where you wrote `"Mick"`.  Try it again;
#> next time's the charm!>

grade_this_code()(
  list(
    .user_code = "ggplot(data = mpg, mapping = aes(x = displ, y = hwy, alpha = class, 0.1)) + geom_point()", 
    .solution_code = "ggplot(data = mpg, mapping = aes(x = displ, y = hwy, alpha = class)) + geom_point()"
  )
)
#> <gradethis_graded_this_code: [Incorrect] I did not expect your call to `aes()` to
#> include `0.1`. You may have included an unnecessary argument, or you may have left
#> out or misspelled an important argument name. Let's try it again.>

demo <- function(x = 1, ...) {
  list(x, ...)
}

gradethis::grade_this_code()(
  list(
    .user_code = "demo(x = 1, 2)", 
    .solution_code = "demo(x = 1)"
  )
)
#> <gradethis_graded_this_code: [Incorrect] I did not expect your call to `demo()`
#> to include `2`. You may have included an unnecessary argument, or you may have
#> left out or misspelled an important argument name. That's okay: you learn more
#> from mistakes than successes. Let's do it one more time.>
```

### CODE REVIEW

File: R/detect_mistakes.R [hunk 1]
```diff
@@ -320,12 +325,13 @@ detect_mistakes <- function(user,
...
   user_args <- as.list(user)[-1]         # remove the call
   solution_args <- as.list(solution)[-1] # remove the call
+  user_named_args_ignore_list <- c()
 
   for (name in solution_names) {
     if (!identical(user[[name]], solution[[name]])) {
       arg_name <- ifelse(name %in% submitted_names, name, "")
       # recover the user submission as provided by only unpiping one level
-      user_submitted <- call_standardise_formals(unpipe(submitted))
+      user_submitted <- call_standardise_formals(unpipe(submitted), env = env)
```
Comment (schloerke) [inline R/detect_mistakes.R:334]: good find

File: R/message_generators.R [hunk 2]
```diff
@@ -357,11 +372,14 @@ wrong_value <- function(this,
...
-      this = this,
+      intro = intro,
+      expected = expected,
       that = that,
+      where = if (!identical(this, "")) where else "",
+      this = this,
       action = action %||% ""
     ),
-    "{intro}I expected {action}{that} where you wrote {this}."
+    "{intro}I {expected} {action}{that}{where}{this}."
```
Comment (schloerke) [inline R/message_generators.R:382]: 😂

File: R/utils.R [hunk 3]
```diff
@@ -6,7 +6,12 @@ is_pipe <- function(x) {
...
 .infixes_assign <- c("<-", "<<-", "->", "->>", "=")
-.infixes <- c("+", "-", "*", "/", "^", "%%", "%/%", "%in%", .infixes_assign)
+.infixes_comp <- c("==", "!=", ">", ">=", "<", "<=")
+.infixes <- c(
+  "+", "-", "*", "/", "^", "$", "[", "[[", "!", "%%", "%/%", "%in%", 
+  .infixes_assign,
+  .infixes_comp
+)
 
 is_infix <- function(x, infix_vals = .infixes) {
```
Comment (schloerke) [inline R/utils.R:17]: Should this function be updated to something like "If function doesn't start with an alpha char, and is a call, then it is an infix op", rather than checking against a white list of functions.

**Review by schloerke — APPROVED** [review]
LGTM.

Maybe infix idea can be done in a later PR

File: R/message_generators.R (hunk 2 above)
Comment (gadenbuie) [reply R/message_generators.R:382]: I suppose I could move the _I_ and the white space into `expected` and make it

```
"{intro}{expected}{action}{that}{where}{this}"
```

😆

File: R/utils.R (hunk 3 above)
Comment (gadenbuie) [reply R/utils.R:17]: Yeah this function feels particularly brittle, especially considering the change I'm making here. Also: we should consider other infix operators defined by other packages, e.g. `%AND%` or `%+%` or other random things.

On the other hand, what about bizarre function names?

```
str2lang("`12`(13)")[[1]]
#> `12`
as.character(str2lang("`12`(13)")[[1]])
#> [1] "12"
```

I'm going to add the change here for now and we can come back to this in a separate PR
