### PR TITLE
res returns a single bool using `all` and raises warning

### LINKED ISSUE #45: Comparing dataframes via `check_result` is causing an `evaluate_condi` error
Conversation from this message: https://github.com/rstudio-education/grader/issues/36#issuecomment-512279957

`learnr` shows an error message and this is what is shown in the r console:

```
Error in evaluate_condition(resu, grader_args, learnr_args): Assertion on 'res' failed: Must be of type 'logical', not 'character'.
```

Reproducible bits below:

### Works in console

```
billboard <- structure(list(year = c(2000, 2000, 2000, 2000, 2000, 2000), 
    artist.inverted = c("Destiny's Child", "Santana", "Savage Garden", 
    "Madonna", "Aguilera, Christina", "Janet"), track = c("Independent Women Part I", 
    "Maria, Maria", "I Knew I Loved You", "Music", "Come On Over Baby (All I Want Is You)", 
    "Doesn't Really Matter"), time = structure(c(13080, 15480, 
    14820, 13500, 13080, 15420), class = c("hms", "difftime"), units = "secs"), 
    genre = c("Rock", "Rock", "Rock", "Rock", "Rock", "Rock"), 
    date.entered = structure(c(11223, 10999, 10887, 11181, 11174, 
    11125), class = "Date"), date.peaked = structure(c(11279, 
    11055, 10985, 11216, 11244, 11195), class = "Date"), x1st.week = c(78, 
    15, 71, 41, 57, 59), x2nd.week = c(63, 8, 48, 23, 47, 52), 
    x3rd.week = c(49, 6, 43, 18, 45, 43), x4th.week = c(33, 5, 
    31, 14, 29, 30), x5th.week = c(23, 2, 20, 2, 23, 29), x6th.week = c(15, 
    3, 13, 1, 18, 22), x7th.week = c(7, 2, 7, 1, 11, 15), x8th.week = c(5, 
    2, 6, 1, 9, 10), x9th.week = c(1, 1, 4, 1, 9, 10), x10th.week = c(1, 
    1, 4, 2, 11, 5), x11th.week = c(1, 1, 4, 2, 1, 1), x12th.week = c(1, 
    1, 6, 2, 1, 1), x13th.week = c(1, 1, 4, 2, 1, 1), x14th.week = c(1, 
    1, 2, 2, 1, 2), x15th.week = c(1, 1, 1, 4, 4, 2), x16th.week = c(1, 
    1, 1, 8, 8, 3), x17th.week = c(1, 1, 1, 11, 12, 3), x18th.week = c(1, 
    1, 2, 16, 22, 7), x19th.week = c(1, 8, 1, 20, 23, 8), x20th.week = c(2, 
    15, 2, 25, 43, 20), x21st.week = c(3, 19, 4, 27, 44, 25), 
    x22nd.week = c(7, 21, 8, 27, NA, 37), x23rd.week = c(10, 
    26, 8, 29, NA, 40), x24th.week = c(12, 36, 12, 44, NA, 41
    ), x25th.week = c(15, 48, 14, NA, NA, NA), x26th.week = c(22, 
    47, 17, NA, NA, NA), x27th.week = c(29, NA, 21, NA, NA, NA
    ), x28th.week = c(31, NA, 24, NA, NA, NA), x29th.week = c(NA, 
    NA, 30, NA, NA, NA), x30th.week = c(NA, NA, 34, NA, NA, NA
    ), x31st.week = c(NA, NA, 37, NA, NA, NA), x32nd.week = c(NA, 
    NA, 46, NA, NA, NA), x33rd.week = c(NA, NA, 47, NA, NA, NA
    ), x34th.week = c(NA_real_, NA_real_, NA_real_, NA_real_, 
    NA_real_, NA_real_), x35th.week = c(NA_real_, NA_real_, NA_real_, 
    NA_real_, NA_real_, NA_real_), x36th.week = c(NA_real_, NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_), x37th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x38th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x39th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x40th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x41st.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x42nd.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x43rd.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x44th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x45th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x46th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x47th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x48th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x49th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x50th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x51st.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x52nd.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x53rd.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x54th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x55th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x56th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x57th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x58th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x59th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x60th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x61st.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x62nd.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x63rd.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x64th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x65th.week = c(NA_real_, 
    NA_real_, NA_real_, NA_real_, NA_real_, NA_real_), x66th.week = c(NA, 
    NA, NA, NA, NA, NA), x67th.week = c(NA, NA, NA, NA, NA, NA
    ), x68th.week = c(NA, NA, NA, NA, NA, NA), x69th.week = c(NA, 
    NA, NA, NA, NA, NA), x70th.week = c(NA, NA, NA, NA, NA, NA
    ), x71st.week = c(NA, NA, NA, NA, NA, NA), x72nd.week = c(NA, 
    NA, NA, NA, NA, NA), x73rd.week = c(NA, NA, NA, NA, NA, NA
    ), x74th.week = c(NA, NA, NA, NA, NA, NA), x75th.week = c(NA, 
    NA, NA, NA, NA, NA), x76th.week = c(NA, NA, NA, NA, NA, NA
    )), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-6L))

user <- reshape2::melt.data.frame(
  head(billboard),
  id.vars = c("year", "artist.inverted", "track", "time",
              "genre", "date.entered", "date.peaked"),
  variable.name = "week",
  value.name = "rank",
  factorAsStrings = TRUE
)
user$week <- as.character(user$week)

solution <- tidyr::gather(head(billboard), "week", "rank", x1st.week:x76th.week)

all.equal(tibble::as_tibble(user), tibble::as_tibble(solution))
```

### Fails in the `learnr` document

````
```{r zuzwislfkfnsoesa, exercise = TRUE}
# student code
user <- reshape2::melt(head(billboard), id.vars = c("year", "artist.inverted", "track",
        time", "genre", "date.entered", "date.peaked"),
    variable.name = "week",
    value.name = "rank",
    factorAsStrings = TRUE
)
user$week <- as.character(user$week)
```

```{r zuzwislfkfnsoesa-check}
solution <- tidyr::gather(head(billboard), "week", "rank", x1st.week:x76th.week)

grader::check_result(
  grader::pass_if(~ all.equal(tibble::as_tibble(.result), tibble::as_tibble(solution)))
)
```
````

### LINKED ISSUE #46: Comparing NA values when solution is not an atomic
There is a difference between `3 == NA` and `NA == NA`. This is probably the notation (`==`) that will be used by instructors, e.g., `pass_if(~ .result == df)`

When `==` is used in a comparison there is a difference between when the user and solution code are both `NA` (maybe should return a `TRUE` match), and when only one of them returns `NA`. Right now they both return `NA`, and I need to set `na.rm = TRUE` to get a boolean value from `all` that is not `NA` if there is a missing value.

Does this mean we need to replace any calls to `==` with `all.equal` or `identical`?

here's a minimal example of what I'm trying to show:

```r
> user <- c(1, 2, 3, NA)
> solution <- c(1, 2, 3, NA) ## both are missing
> user == solution
[1] TRUE TRUE TRUE   NA
> all(user == solution)
[1] NA
```

```r
> user <- c(1, 2, 3, NA)
> solution <- c(1, 2, 3, 4) ##  the solutions don't actually match
> user == solution
[1] TRUE TRUE TRUE   NA
> all(user == solution, na.rm = TRUE)
[1] TRUE
```

### PR DESCRIPTION
**Pull request by chendaniely**
Fixes #45 (comparing df with `check_result`), and fixes #46 (dealing with `NA` values) by returning a warning.

Taken from internal discussion:

we’re fixing this error with a three-pronged approach:
https://github.com/rstudio-education/grader/blob/787c955162831c593d2e84b9a517845e103d0052/R/pass_fail_condi.R#L72

- [x]  In documentation, tell everyone to use identical() all the time, never `==`
- [x]  Line 72, if clause tries to fix things if they use `==`
- [x]  Line 72, if clause raises a `warning` to the console (somehow) that tells the teacher to use `identical` instead of `==`

### CODE REVIEW

**Comment by chendaniely** [comment]
build is failing because of libraries used in unittests

```
* checking for unstated dependencies in ‘tests’ ... WARNING
'::' or ':::' imports not declared from:
  ‘reshape2’ ‘tibble’ ‘tidyr’
```

should these libraries be added to the suggests section in `DESCRIPTION`?

File: tests/testthat/test_check_result_df.R [hunk 1]
```diff
@@ -0,0 +1,112 @@
...
+  value.name = "rank",
+  factorAsStrings = TRUE
+)
+user$week <- as.character(user$week)
+solution <- tidyr::gather(head(billboard), "week", "rank", x1st.week:x76th.week)
+
+user <- tibble::as_tibble(user)
+solution <- tibble::as_tibble(solution)
+
+test_that("Comparing dataframes, testing for null env", {
```
Comment (schloerke) [inline tests/testthat/test_check_result_df.R]: need to insert a `skip_if_not_installed("tidyr")`. Should be done with all suggested packages

File: tests/testthat/test_check_result_df.R [hunk 2]
```diff
@@ -0,0 +1,112 @@
...
+    NA, NA, NA, NA, NA), x70th.week = c(NA, NA, NA, NA, NA, NA
+    ), x71st.week = c(NA, NA, NA, NA, NA, NA), x72nd.week = c(NA, 
+    NA, NA, NA, NA, NA), x73rd.week = c(NA, NA, NA, NA, NA, NA
+    ), x74th.week = c(NA, NA, NA, NA, NA, NA), x75th.week = c(NA, 
+    NA, NA, NA, NA, NA), x76th.week = c(NA, NA, NA, NA, NA, NA
+    )), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
+-6L))
+# nolint end
+
+user <- reshape2::melt(
```
Comment (schloerke) [inline tests/testthat/test_check_result_df.R]: move this inside the test / helper function

**Comment by chendaniely** [comment]
@garrettgman Adding the warning shows up in the console. Here's the full list of things I see at the moment, not sure how to deal with the other messages...

```
Output created: Lightning-Talk.html

Listening on http://127.0.0.1:4952
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata,
  e.g. by using --metadata pagetitle="..." on the command line.
  Falling back to 'exercise.knit.utf8'
Registered S3 method overwritten by 'pryr':
  method      from
  print.bytes Rcpp
Warning: Calling `as_tibble()` on a vector is discouraged, because the behavior is likely to change in the future. Use `tibble::enframe(name = NULL)` instead.
This warning is displayed once per session.
Warning in evaluate_condition(resu, grader_args, learnr_args) :
  I got a length of 2, instead of 1 during the conditional check.
Did you use == ? If so, consider using idential()
Warning in all(res, na.rm = TRUE) :
  coercing argument of type 'character' to logical
Warning in selectChildren(jobs, timeout) :
  cannot wait for child 25839 as it does not exist
```

**Comment by chendaniely** [comment]
travis is failing because of the image...

```
resolvconf start/running
R for Travis-CI is not officially supported, but is community maintained.
Please file any issues at https://travis-ci.community/c/languages/r
and mention @jeroen and @jimhester in the issue
Installing R
254.77s$ sudo add-apt-repository -y "ppa:marutter/rrutter3.5"
Cannot add PPA: 'ppa:marutter/rrutter3.5'.
Please check that the PPA name or format is correct.
The command "sudo add-apt-repository -y "ppa:marutter/rrutter3.5"" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by chendaniely** [comment]
nevermind, seemed like an internal travis hickup

File: tests/testthat/test_check_result_df.R [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+  solution <- tidyr::gather(head(billboard), "week", "rank", x1st.week:x76th.week)
+  return(solution)
+}
+
+test_that("Comparing dataframes, testing for null env", {
+  skip_if_not_installed("reshape2")
+  skip_if_not_installed("tidyr")
+  skip_if_not_installed("tibble")
+
+  user <- tibble::as_tibble(create_user_df_melt())
```
Comment (schloerke) [inline tests/testthat/test_check_result_df.R]: * Save the final dput value of `user` and `solution` to `billboard.R` file in `./tests/testthat`.  
* Source `billboard.R` at the top of this this to load the data
* Add the code to produce `./tests/testthat/billboard.R` to `./scripts/billboard.R`. (Use what ever package you'd like)
* Remove suggested packages

File: R/pass_fail_condi.R [hunk 4]
```diff
@@ -67,6 +67,16 @@ evaluate_condition <- function(condi, grader_args, learnr_args) {
...
          )
 
+  # if we compare something like a vector or dataframes to one another
+  # we need to collapse the result down to a single boolean value
+  if (length(res) > 1) {
+    ## this isn't the best way to handle NA values so we raise a warning.
+    ## https://github.com/rstudio-education/grader/issues/46 # nolint
+    warning(glue::glue("I got a length of {length(res)}, instead of 1 during the conditional check.
+      Did you use == ? If so, consider using idential()")) # nolint
+    res <- all(res, na.rm = TRUE)
```
Comment (schloerke) [inline R/pass_fail_condi.R]: `all(c(NA, NA), na.rm = TRUE)` is `TRUE`.

Maybe add in a 

```r
!all(is.na(res)) && all(res, na.rm = TRUE)
```

File: R/pass_fail_condi.R [hunk 5]
```diff
@@ -67,6 +67,16 @@ evaluate_condition <- function(condi, grader_args, learnr_args) {
            "value" = evaluate_condi_value(condi$x, learnr_args$last_value)
          )
 
+  # if we compare something like a vector or dataframes to one another
+  # we need to collapse the result down to a single boolean value
+  if (length(res) > 1) {
+    ## this isn't the best way to handle NA values so we raise a warning.
+    ## https://github.com/rstudio-education/grader/issues/46 # nolint
+    warning(glue::glue("I got a length of {length(res)}, instead of 1 during the conditional check.
```
Comment (schloerke) [inline R/pass_fail_condi.R]: remove return and use `\n` instead

File: R/pass_fail_condi.R [hunk 6]
```diff
@@ -67,6 +67,16 @@ evaluate_condition <- function(condi, grader_args, learnr_args) {
            "value" = evaluate_condi_value(condi$x, learnr_args$last_value)
          )
 
+  # if we compare something like a vector or dataframes to one another
+  # we need to collapse the result down to a single boolean value
+  if (length(res) > 1) {
```
Comment (schloerke) [inline R/pass_fail_condi.R]: Maybe also check for size = 0?

```r
if (length(res) == 0) {
  warning(glue::glue("I got a length of {length(res)}, instead of 1 during the conditional check.\nDid you use == ? If so, consider using idential()")) # nolint
  res <- FALSE
}
```

Comment (chendaniely) [reply R/pass_fail_condi.R]: the check for size = 0 is already made in the checkmate call

https://github.com/rstudio-education/grader/blob/d678f79e488dafc12781b59a0055e3f3c96b3b4b/R/pass_fail_condi.R#L85
